name: Publish
on:
  release:
    types: [published]
jobs:
  publish:
    name: Publish
    runs-on: macOS-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Validation
        run: true && [ "${GITHUB_REF##*/}" = "$(cat .version)" ]

      - name: Get ruby gem cache
        id: gem-cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-1-gem-${{ hashFiles('Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-1-gem-

      - name: Install ruby gems
        if: steps.gem-cache.cache.outputs.cache-hit != 'true'
        run: make gem

      - name: CocoaPods trunk push
        run: make pod-release
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
